### ISSUE TITLE
Error in Colab

### ISSUE THREAD

**Issue by Alek2345** [djbielejeski/a-person-mask-generator#12]
The Img tab does not show the picture. When I try to generate it, it gives an error. Please help/!

Error running before_process: /content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/a-person-mask-generator/scripts/a_person_mask_generator.py
    Traceback (most recent call last):
      File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/scripts.py", line 611, in before_process
        script.before_process(p, *script_args)
      File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/a-person-mask-generator/scripts/a_person_mask_generator.py", line 293, in before_process
        p.image_mask = self.generate_mask(image=p.init_images[-1], mask_targets=mask_targets)
      File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/a-person-mask-generator/scripts/a_person_mask_generator.py", line 65, in generate_mask
        options = ImageSegmenterOptions(base_options=BaseOptions(model_asset_path=model_path),
    TypeError: ImageSegmenterOptions.__init__() got an unexpected keyword argument 'output_category_mask'

**Comment by nmarafo** [comment]
add this code before launch Automatic1111:
```!pip install mediapipe --upgrade```
it works for me

**Comment by agarzon** [comment]
> `!pip install mediapipe --upgrade`

This actually fixes my issue: https://github.com/djbielejeski/a-person-mask-generator/issues/16 
a shame the dependency management its not well done.
