### ISSUE TITLE
Error on launch

### ISSUE THREAD

**Issue by agarzon** [djbielejeski/a-person-mask-generator#16]
`*** Error loading script: a_person_mask_generator.py
    Traceback (most recent call last):
      File "D:\SD\Data\Packages\Stable Diffusion WebUI\modules\scripts.py", line 382, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "D:\SD\Data\Packages\Stable Diffusion WebUI\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "D:\SD\Data\Packages\Stable Diffusion WebUI\extensions\a-person-mask-generator\scripts\a_person_mask_generator.py", line 8, in <module>
        import mediapipe as mp
    ModuleNotFoundError: No module named 'mediapipe'`

**Comment by rabbitflyer** [comment]
Have you tried manually

**Comment by rabbitflyer** [comment]
Seems like a venv issue; have you tried manually (re)installing mediapipe in the SD venv with pip?

**Comment by agarzon** [comment]
> Seems like a venv issue; have you tried manually (re)installing mediapipe in the SD venv with pip?

No, I did not yet, I was expecting the extension to work out of the box.

**Comment by agarzon** [comment]
I can provide more insight:

Log when it is installed fresh in a new A1111 setup: 

```
Installing a-person-mask-generator requirement: mediapipe
Couldn't install a-person-mask-generator requirement: mediapipe.
Command: "D:\SD\Data\Packages\Stable Diffusion WebUI\venv\Scripts\python.exe" -m pip install mediapipe --prefer-binary
Error code: 1
stdout: Collecting mediapipe
  Using cached mediapipe-0.10.8-cp310-cp310-win_amd64.whl.metadata (9.8 kB)
Requirement already satisfied: absl-py in d:\sd\data\packages\stable diffusion webui\venv\lib\site-packages (from mediapipe) (2.0.0)
Requirement already satisfied: attrs>=19.1.0 in d:\sd\data\packages\stable diffusion webui\venv\lib\site-packages (from mediapipe) (23.1.0)
Requirement already satisfied: flatbuffers>=2.0 in d:\sd\data\packages\stable diffusion webui\venv\lib\site-packages (from mediapipe) (23.5.26)
Requirement already satisfied: matplotlib in d:\sd\data\packages\stable diffusion webui\venv\lib\site-packages (from mediapipe) (3.8.0)
Requirement already satisfied: numpy in d:\sd\data\packages\stable diffusion webui\venv\lib\site-packages (from mediapipe) (1.23.5)
Collecting opencv-contrib-python (from mediapipe)
  Using cached opencv_contrib_python-4.8.1.78-cp37-abi3-win_amd64.whl.metadata (20 kB)
Requirement already satisfied: protobuf<4,>=3.11 in d:\sd\data\packages\stable diffusion webui\venv\lib\site-packages (from mediapipe) (3.20.3)
Collecting sounddevice>=0.4.4 (from mediapipe)
  Using cached sounddevice-0.4.6-py3-none-win_amd64.whl (199 kB)
Collecting CFFI>=1.0 (from sounddevice>=0.4.4->mediapipe)
  Using cached cffi-1.16.0-cp310-cp310-win_amd64.whl.metadata (1.5 kB)
Requirement already satisfied: contourpy>=1.0.1 in d:\sd\data\packages\stable diffusion webui\venv\lib\site-packages (from matplotlib->mediapipe) (1.1.1)
Requirement already satisfied: cycler>=0.10 in d:\sd\data\packages\stable diffusion webui\venv\lib\site-packages (from matplotlib->mediapipe) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in d:\sd\data\packages\stable diffusion webui\venv\lib\site-packages (from matplotlib->mediapipe) (4.43.1)
Requirement already satisfied: kiwisolver>=1.0.1 in d:\sd\data\packages\stable diffusion webui\venv\lib\site-packages (from matplotlib->mediapipe) (1.4.5)
Requirement already satisfied: packaging>=20.0 in d:\sd\data\packages\stable diffusion webui\venv\lib\site-packages (from matplotlib->mediapipe) (23.2)
Requirement already satisfied: pillow>=6.2.0 in d:\sd\data\packages\stable diffusion webui\venv\lib\site-packages (from matplotlib->mediapipe) (9.5.0)
Requirement already satisfied: pyparsing>=2.3.1 in d:\sd\data\packages\stable diffusion webui\venv\lib\site-packages (from matplotlib->mediapipe) (3.1.1)
Requirement already satisfied: python-dateutil>=2.7 in d:\sd\data\packages\stable diffusion webui\venv\lib\site-packages (from matplotlib->mediapipe) (2.8.2)
Requirement already satisfied: pycparser in d:\sd\data\packages\stable diffusion webui\venv\lib\site-packages (from CFFI>=1.0->sounddevice>=0.4.4->mediapipe) (2.21)
Requirement already satisfied: six>=1.5 in d:\sd\data\packages\stable diffusion webui\venv\lib\site-packages (from python-dateutil>=2.7->matplotlib->mediapipe) (1.16.0)
Using cached mediapipe-0.10.8-cp310-cp310-win_amd64.whl (50.5 MB)
Using cached opencv_contrib_python-4.8.1.78-cp37-abi3-win_amd64.whl (44.8 MB)
Using cached cffi-1.16.0-cp310-cp310-win_amd64.whl (181 kB)
Installing collected packages: opencv-contrib-python, CFFI, sounddevice, mediapipe

stderr: DEPRECATION: torchsde 0.2.5 has a non-standard dependency specifier numpy>=1.19.*; python_version >= "3.7". pip 24.0 will enforce this behaviour change. A possible replacement is to upgrade to a newer version of torchsde or contact the author to suggest that they release a version with a conforming dependency specifiers. Discussion can be found at https://github.com/pypa/pip/issues/12063
ERROR: Could not install packages due to an OSError: [WinError 5] Access is denied: 'D:\\SD\\Data\\Packages\\Stable Diffusion WebUI\\venv\\Lib\\site-packages\\cv2\\cv2.pyd'
Check the permissions.


a-person-mask-generator: Warning: Failed to install mediapipe.
```

**Comment by rabbitflyer** [comment]
That's a file permissions error. Make sure that you can create files in the directory "D:\SD\Data\Packages\Stable Diffusion WebUI\venv\Lib\site-packages\cv2" (or its parent if it doesn't exist).

Not sure if this is the original issue you were dealing with though, if this is a different A1111 instance.

**Comment by agarzon** [comment]
> That's a file permissions error. Make sure that you can create files in the directory "D:\SD\Data\Packages\Stable Diffusion WebUI\venv\Lib\site-packages\cv2" (or its parent if it doesn't exist).
> 
> Not sure if this is the original issue you were dealing with though, if this is a different A1111 instance.

It was fixed by doing this: https://github.com/djbielejeski/a-person-mask-generator/issues/12#issuecomment-1826880923
