### ISSUE TITLE
Installation issues

### ISSUE THREAD

**Issue by PLFENG** [djbielejeski/a-person-mask-generator#23]
Traceback (most recent call last):
  File "E:\ComfyUI\Blender_ComfyUI\ComfyUI\custom_nodes\a-person-mask-generator\install.py", line 1, in <module>
    import launch
  File "E:\ComfyUI\Blender_ComfyUI\python_embeded\lib\site-packages\launch\__init__.py", line 9, in <module>
    from .cli import *
  File "E:\ComfyUI\Blender_ComfyUI\python_embeded\lib\site-packages\launch\cli.py", line 12, in <module>
    from .app import App
  File "E:\ComfyUI\Blender_ComfyUI\python_embeded\lib\site-packages\launch\app.py", line 11, in <module>
    from flowdas import meta
ImportError: cannot import name 'meta' from 'flowdas' (E:\ComfyUI\Blender_ComfyUI\python_embeded\lib\site-packages\flowdas\__init__.py)

**Comment by avachon100510** [comment]
Apparently, the launch module is deprecated and cannot be installed with pip... there needs to be a change in the install.py file.

**Comment by Falkonar** [comment]
the same...

**Comment by Spawnfile** [comment]
Hello there, you need to change install.py file depending on my PR. Hope this helps. 

https://github.com/djbielejeski/a-person-mask-generator/pull/32

**Comment by djbielejeski** [comment]
Fixed here: https://github.com/djbielejeski/a-person-mask-generator/pull/33
