### ISSUE TITLE
no mask generated, ***Error running before_process

### ISSUE THREAD

**Issue by bczican** [djbielejeski/a-person-mask-generator#24]
When I enable the extension, the mask preview is blank.  If I click generate, it gives me this error.

*** Error running before_process: G:\AI\StableDiffusion\stable-diffusion-webui\extensions\a-person-mask-generator\scripts\a_person_mask_generator.py
    Traceback (most recent call last):
      File "G:\AI\StableDiffusion\stable-diffusion-webui\modules\scripts.py", line 710, in before_process
        script.before_process(p, *script_args)
      File "G:\AI\StableDiffusion\stable-diffusion-webui\extensions\a-person-mask-generator\scripts\a_person_mask_generator.py", line 310, in before_process
        p.image_mask = self.generate_mask(image=p.init_images[-1], mask_targets=mask_targets, mask_dilation=inpaint_dilation)
      File "G:\AI\StableDiffusion\stable-diffusion-webui\extensions\a-person-mask-generator\scripts\a_person_mask_generator.py", line 65, in generate_mask
        options = ImageSegmenterOptions(base_options=BaseOptions(model_asset_path=model_path),
    TypeError: ImageSegmenterOptions.__init__() got an unexpected keyword argument 'output_category_mask'

**Comment by beansfotos** [comment]
Same!!!!

**Comment by djbielejeski** [comment]
You may need to update your mediapipe package.
