### ISSUE TITLE
Error loading script

### ISSUE THREAD

**Issue by artkrylov** [djbielejeski/a-person-mask-generator#6]
Hi! Thank you for the extension, but I was unable to install it. 

Mac mini M1 8Gb 
A1111 version: v1.6.0-2-g4afaaf8a 
`  ./webui.sh --opt-split-attention-v1`

```
*** Error loading script: a_person_mask_generator.py
    Traceback (most recent call last):
      File "/Users/admin/Documents/projects/sd/modules/scripts.py", line 382, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "/Users/admin/Documents/projects/sd/modules/script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "/Users/admin/Documents/projects/sd/extensions/a-person-mask-generator/scripts/a_person_mask_generator.py", line 8, in <module>
        import mediapipe as mp
      File "/Users/admin/Documents/projects/sd/venv/lib/python3.10/site-packages/mediapipe/__init__.py", line 16, in <module>
        import mediapipe.python.solutions as solutions
      File "/Users/admin/Documents/projects/sd/venv/lib/python3.10/site-packages/mediapipe/python/solutions/__init__.py", line 17, in <module>
        import mediapipe.python.solutions.drawing_styles
      File "/Users/admin/Documents/projects/sd/venv/lib/python3.10/site-packages/mediapipe/python/solutions/drawing_styles.py", line 20, in <module>
        from mediapipe.python.solutions.drawing_utils import DrawingSpec
      File "/Users/admin/Documents/projects/sd/venv/lib/python3.10/site-packages/mediapipe/python/solutions/drawing_utils.py", line 24, in <module>
        from mediapipe.framework.formats import detection_pb2
      File "/Users/admin/Documents/projects/sd/venv/lib/python3.10/site-packages/mediapipe/framework/formats/detection_pb2.py", line 5, in <module>
        from google.protobuf.internal import builder as _builder
    ImportError: cannot import name 'builder' from 'google.protobuf.internal' (/Users/admin/Documents/projects/sd/venv/lib/python3.10/site-packages/google/protobuf/internal/__init__.py)
   ```

**Comment by djbielejeski** [comment]
Sorry I do not have a M1 or M2 mac to test and fix this issue.  PR's welcome though!

**Comment by Osato28** [comment]
I have an M1 Mac, and I couldn't replicate this. Looks like an issue with your installation of protobuf. TensorFlow sometimes has that problem, judging by what Google turned up.

Try the following:

1) Check if the file `builder.py` exists at `/Users/admin/Documents/projects/sd/venv/lib/python3.10/site-packages/google/protobuf/internal/`.

2) If it's missing, upgrade protobuf via pip (`pip install --upgrade protobuf`), then download latest builder.py from GitHub into that folder:

`wget https://raw.githubusercontent.com/protocolbuffers/protobuf/main/python/google/protobuf/internal/builder.py -O /Users/admin/Documents/projects/sd/venv/lib/python3.10/site-packages/google/protobuf/internal/builder.py`

**Comment by djbielejeski** [comment]
Thanks @Osato28, closing this issue.

**Comment by artkrylov** [comment]
@Osato28 Thank you! It works!
